service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  profile: nodejs-aws-2023q1-q2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:us-east-1:*:table/*

  environment:
    DB_PRODUCTS_TABLE: AWS_CloudX_Course_Products
    DB_STOCKS_TABLE: AWS_CloudX_Course_Stocks

functions:
  getProductsList:
    handler: handlers.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
  getAvailableProductsList:
    handler: handlers.getAvailableProductsList
    events:
      - httpApi:
          path: /products/available
          method: get
  getProductById:
    handler: handlers.getProductById
    events:
      - httpApi:
          path: /products/{id}
          method: get

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
